[advisories]
db-path = "advisory-db"
git-fetch-with-cli = true

[licenses]
allow = ["MIT", "Apache-2.0", "BSD-3-Clause", "BSD-2-Clause", "ISC", "Zlib", "Unicode-3.0", "MPL-2.0", "Apache-2.0 WITH LLVM-exception"]

