name: Lint

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  clippy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile: [debug, release]
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features -D warnings --profile ${{ matrix.profile }}
