name: pr-checklist
on:
  pull_request_target:
    types: [opened, edited, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        id: body
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });
            const body = pr.data.body || '';
            const boxes = ['property test updated','migration script added if needed','diagrams refreshed','loom coverage ID'];
            const ok = boxes.every(b => body.includes(`- [x] ${b}`));
            if (!ok) {
              core.setFailed('Checklist incomplete');
            }
